networks:
  bookstore:
    driver: bridge

services:
  database:
    image: postgres:17.4
    networks:
      - bookstore
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
